In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\User\Downloads\Dataset_Uber Traffic.csv",sep=',') #loading data using pandas

In [3]:
df.shape
# there are 48,120 rows and 4 columns

(48120, 4)

In [4]:
df.head()
# this is how the data is

        DateTime  Junction  Vehicles           ID
0  01/11/15 0:00         1        15  20151101001
1  01/11/15 1:00         1        13  20151101011
2  01/11/15 2:00         1        10  20151101021
3  01/11/15 3:00         1         7  20151101031
4  01/11/15 4:00         1         9  20151101041

In [5]:
df.info()
# The DateTime is in the object data type we need to change it

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DateTime  48120 non-null  object
 1   Junction  48120 non-null  int64
 2   Vehicles  48120 non-null  int64
 3   ID        48120 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [6]:
df.describe()

           Junction      Vehicles            ID
count  48120.000000  48120.000000  4.812000e+04
mean       2.180549     22.791334  2.016330e+10
std        0.966955     20.750063  5.944854e+06
min        1.000000      1.000000  2.015110e+10
25%        1.000000      9.000000  2.016042e+10
50%        2.000000     15.000000  2.016093e+10
75%        3.000000     29.000000  2.017023e+10
max        4.000000    180.000000  2.017063e+10

In [7]:
df["DateTime"] = pd.to_datetime(
    df["DateTime"],
    format="%d/%m/%y %H:%M"
) # change the DateTime data type

In [9]:
df.info()
# now its good

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DateTime  48120 non-null  datetime64[ns]
 1   Junction  48120 non-null  int64
 2   Vehicles  48120 non-null  int64
 3   ID        48120 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 1.5 MB

In [10]:
# Checking for duplicate records
df.duplicated().sum()

0

In [11]:
df.drop_duplicates(inplace=True) 
# it help's to drop duplicates records

In [12]:
df["ID"].duplicated().sum()
# there is no duplicate id also

0

In [13]:
# Checking missing values
df.isnull().sum()
#there is no missing values

DateTime    0
Junction    0
Vehicles    0
ID          0
dtype: int64

In [14]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage
#checking as percentage still no missing values

DateTime    0.0
Junction    0.0
Vehicles    0.0
ID          0.0
dtype: float64

In [18]:
print("Junctions",df["Junction"].unique())
#checking the junction numbers
df["Junction"].value_counts()

Junctions [1 2 3 4]

Junction
1    14592
2    14592
3    14592
4     4344
Name: count, dtype: int64

In [20]:
# Checking for invalid traffic values
# Traffic volume should normally not be negative
df[df["Vehicles"] < 0]

Empty DataFrame
Columns: [DateTime, Junction, Vehicles, ID]
Index: []

In [21]:
print("Negative vehicle values:", (df["Vehicles"] < 0).sum())

Negative vehicle values: 0

In [22]:
print("Zero vehicle values:", (df["Vehicles"] == 0).sum())

Zero vehicle values: 0

In [23]:
print("Minimum Vehicles:", df["Vehicles"].min())
print("Maximum Vehicles:", df["Vehicles"].max())
#we already seen this data in describe() also

Minimum Vehicles: 1
Maximum Vehicles: 180

In [24]:
# Creating time features
df["Year"] = df["DateTime"].dt.year
df["Month"] = df["DateTime"].dt.month
df["Day"] = df["DateTime"].dt.day
df["Hour"] = df["DateTime"].dt.hour
df["DayOfWeek"] = df["DateTime"].dt.dayofweek

In [25]:
df.head()
# here we created the time features

,DateTime,Junction,Vehicles,ID,Year,Month,Day,Hour,DayOfWeek
0,2015-11-01 00:00:00,1,15,20151101001,2015,11,1,0,6
1,2015-11-01 01:00:00,1,13,20151101011,2015,11,1,1,6
2,2015-11-01 02:00:00,1,10,20151101021,2015,11,1,2,6
3,2015-11-01 03:00:00,1,7,20151101031,2015,11,1,3,6
4,2015-11-01 04:00:00,1,9,20151101041,2015,11,1,4,6

In [26]:
df["DayName"] = df["DateTime"].dt.day_name()

In [27]:
df["IsWeekend"] = np.where(
    df["DayOfWeek"] >= 5,
    1,
    0
) #this code will return 1 if it's a weekend else 0 weekdays "i only taking sunday as weekend"

In [28]:
# Creating a date column
# For event and holiday data, we need a date-only column
df["Date"] = df["DateTime"].dt.date

In [29]:
df[["DateTime", "Date"]].head()

             DateTime        Date
0 2015-11-01 00:00:00  2015-11-01
1 2015-11-01 01:00:00  2015-11-01
2 2015-11-01 02:00:00  2015-11-01
3 2015-11-01 03:00:00  2015-11-01
4 2015-11-01 04:00:00  2015-11-01

In [31]:
df = df.sort_values(
    by=["Junction", "DateTime"]
).reset_index(drop=True) 
#i am sorting the data by Junction then DateTime

In [32]:
df.head()

,DateTime,Junction,Vehicles,ID,Year,Month,Day,Hour,DayOfWeek,DayName,IsWeekend,Date
0,2015-11-01 00:00:00,1,15,20151101001,2015,11,1,0,6,Sunday,1,2015-11-01
1,2015-11-01 01:00:00,1,13,20151101011,2015,11,1,1,6,Sunday,1,2015-11-01
2,2015-11-01 02:00:00,1,10,20151101021,2015,11,1,2,6,Sunday,1,2015-11-01
3,2015-11-01 03:00:00,1,7,20151101031,2015,11,1,3,6,Sunday,1,2015-11-01
4,2015-11-01 04:00:00,1,9,20151101041,2015,11,1,4,6,Sunday,1,2015-11-01

In [33]:
# # save the cleaned data 
# df.to_csv(
#     "cleaned_traffic_data.csv",
#     index=False
# )

#### The source dataset does not provide geographic metadata, so proxy data was used to demonstrate the multi-source integration pipeline

In [34]:
# Creating proxy historical weather data
print("Start Date:", df["DateTime"].min())
print("End Date:", df["DateTime"].max())

Start Date: 2015-11-01 00:00:00
End Date: 2017-06-30 23:00:00

In [35]:
# creating an hourly weather timeline
weather_datetime = pd.date_range(
    start=df["DateTime"].min(),
    end=df["DateTime"].max(),
    freq="h"
)

weather_df = pd.DataFrame({
    "DateTime": weather_datetime
})

weather_df.head()

             DateTime
0 2015-11-01 00:00:00
1 2015-11-01 01:00:00
2 2015-11-01 02:00:00
3 2015-11-01 03:00:00
4 2015-11-01 04:00:00

#### Creating weather variables

In [36]:
# creating proxy values for pipeline development
# Using a fixed random seed so your results remain reproducible
np.random.seed(42)

In [37]:
weather_df["Temperature"] = np.random.normal(
    loc=25,
    scale=5,
    size=len(weather_df)
)

weather_df["Humidity"] = np.random.normal(
    loc=65,
    scale=15,
    size=len(weather_df)
)

weather_df["WindSpeed"] = np.random.normal(
    loc=12,
    scale=5,
    size=len(weather_df)
)

weather_df["Precipitation"] = np.random.exponential(
    scale=1.5,
    size=len(weather_df)
)

In [38]:
weather_df.head()

             DateTime  Temperature   Humidity  WindSpeed  Precipitation
0 2015-11-01 00:00:00    27.483571  83.336032  14.032522       0.720668
1 2015-11-01 01:00:00    24.308678  65.932688  10.547684       1.801207
2 2015-11-01 02:00:00    28.238443  36.807996  23.996886       0.966884
3 2015-11-01 03:00:00    32.615149  38.045125  16.149460       0.815534
4 2015-11-01 04:00:00    23.829233  67.431285   9.726331       1.670036

In [39]:
# correcting inconsistencies
weather_df["Humidity"] = weather_df["Humidity"].clip(
    lower=0,
    upper=100
)

weather_df["WindSpeed"] = weather_df["WindSpeed"].clip(
    lower=0
)

weather_df["Precipitation"] = weather_df["Precipitation"].clip(
    lower=0
)

In [40]:
weather_df["Temperature"] = weather_df["Temperature"].round(2)
weather_df["Humidity"] = weather_df["Humidity"].round(2)
weather_df["WindSpeed"] = weather_df["WindSpeed"].round(2)
weather_df["Precipitation"] = weather_df["Precipitation"].round(2)

In [41]:
weather_df.head()

             DateTime  Temperature  Humidity  WindSpeed  Precipitation
0 2015-11-01 00:00:00        27.48     83.34      14.03           0.72
1 2015-11-01 01:00:00        24.31     65.93      10.55           1.80
2 2015-11-01 02:00:00        28.24     36.81      24.00           0.97
3 2015-11-01 03:00:00        32.62     38.05      16.15           0.82
4 2015-11-01 04:00:00        23.83     67.43       9.73           1.67

#### To demonstrate the cleaning pipeline, we can introduce a small number of missing values only into the proxy weather data

In [47]:
missing_indices = np.random.choice(
    weather_df.index,
    size=100,
    replace=False
)

weather_df.loc[
    missing_indices,
    "Temperature"
] = np.nan

In [48]:
weather_df.isnull().sum()

DateTime           0
Temperature      100
Humidity           0
WindSpeed          0
Precipitation      0
dtype: int64

In [49]:
# Handling missing weather values
weather_df["Temperature"] = (
    weather_df["Temperature"]
    .interpolate(method="linear")
)

In [50]:
weather_df.isnull().sum()

DateTime         0
Temperature      0
Humidity         0
WindSpeed        0
Precipitation    0
dtype: int64

In [51]:
#Checking weather duplicates
weather_df.duplicated().sum()

0

In [52]:
# checking duplicate timestamps
weather_df["DateTime"].duplicated().sum()

0

In [53]:
weather_df.shape

(14592, 5)

In [54]:
# # Save proxy weather data
# weather_df.to_csv(
#     "proxy_weather_data.csv",
#     index=False
# )

#### Creating the event dataset

In [55]:
# creating all unique dates
event_df = pd.DataFrame({
    "Date": pd.date_range(
        start=df["DateTime"].min().date(),
        end=df["DateTime"].max().date(),
        freq="D"
    )
})

In [57]:
event_df.head()

        Date
0 2015-11-01
1 2015-11-02
2 2015-11-03
3 2015-11-04
4 2015-11-05

In [58]:
# Creating event features
np.random.seed(42)

event_df["SportsEvent"] = np.random.choice(
    [0, 1],
    size=len(event_df),
    p=[0.95, 0.05]
)

event_df["Concert"] = np.random.choice(
    [0, 1],
    size=len(event_df),
    p=[0.97, 0.03]
)

event_df["PublicDemonstration"] = np.random.choice(
    [0, 1],
    size=len(event_df),
    p=[0.99, 0.01]
)

In [60]:
event_df["IsHoliday"] = np.nan

In [61]:
event_df["HasEvent"] = np.where(
    (
        (event_df["SportsEvent"] == 1) |
        (event_df["Concert"] == 1) |
        (event_df["PublicDemonstration"] == 1)
    ),
    1,
    0
)

In [62]:
event_df.head()

        Date  SportsEvent  Concert  PublicDemonstration  IsHoliday  HasEvent
0 2015-11-01            0        0                    0        NaN         0
1 2015-11-02            1        0                    0        NaN         1
2 2015-11-03            0        0                    0        NaN         0
3 2015-11-04            0        0                    0        NaN         0
4 2015-11-05            0        0                    0        NaN         0

#### Checking event distribution

In [64]:
event_df[
    [
        "SportsEvent",
        "Concert",
        "PublicDemonstration",
        "HasEvent"
    ]
].sum()

SportsEvent            36
Concert                16
PublicDemonstration     8
HasEvent               56
dtype: int64

In [65]:
event_df["HasEvent"].value_counts()

HasEvent
0    552
1     56
Name: count, dtype: int64

In [66]:
# Saving the event data 
event_df.to_csv(
    "synthetic_event_data.csv",
    index=False
)

#### Prepare the data types before merging

In [67]:
df["DateTime"] = pd.to_datetime(df["DateTime"])
weather_df["DateTime"] = pd.to_datetime(
    weather_df["DateTime"]
)

df["Date"] = pd.to_datetime(df["Date"])
event_df["Date"] = pd.to_datetime(
    event_df["Date"]
)

In [80]:
print(df["DateTime"].dtype)
print(weather_df["DateTime"].dtype)

print(df["Date"].dtype)
print(event_df["Date"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

#### Merge traffic and weather data

In [81]:
merged_df = pd.merge(
    df,
    weather_df,
    on="DateTime",
    how="left"
)

In [82]:
merged_df.head()

,DateTime,Junction,Vehicles,ID,Year,Month,Day,Hour,DayOfWeek,DayName,IsWeekend,Date,Temperature,Humidity,WindSpeed,Precipitation
0,2015-11-01 00:00:00,1,15,20151101001,2015,11,1,0,6,Sunday,1,2015-11-01,27.48,83.34,14.03,0.72
1,2015-11-01 01:00:00,1,13,20151101011,2015,11,1,1,6,Sunday,1,2015-11-01,24.31,65.93,10.55,1.80
2,2015-11-01 02:00:00,1,10,20151101021,2015,11,1,2,6,Sunday,1,2015-11-01,28.24,36.81,24.00,0.97
3,2015-11-01 03:00:00,1,7,20151101031,2015,11,1,3,6,Sunday,1,2015-11-01,32.62,38.05,16.15,0.82
4,2015-11-01 04:00:00,1,9,20151101041,2015,11,1,4,6,Sunday,1,2015-11-01,23.83,67.43,9.73,1.67

In [83]:
print("Original Traffic Rows:", len(df))
print("After Weather Merge:", len(merged_df))

Original Traffic Rows: 48120
After Weather Merge: 48120

In [84]:
merged_df.isnull().sum()

DateTime         0
Junction         0
Vehicles         0
ID               0
Year             0
Month            0
Day              0
Hour             0
DayOfWeek        0
DayName          0
IsWeekend        0
Date             0
Temperature      0
Humidity         0
WindSpeed        0
Precipitation    0
dtype: int64

#### Merge event data

In [85]:
merged_df = pd.merge(
    merged_df,
    event_df,
    on="Date",
    how="left"
)

In [86]:
merged_df.head()

,DateTime,Junction,Vehicles,ID,Year,Month,Day,Hour,DayOfWeek,DayName,...,Date,Temperature,Humidity,WindSpeed,Precipitation,SportsEvent,Concert,PublicDemonstration,IsHoliday,HasEvent
0,2015-11-01 00:00:00,1,15,20151101001,2015,11,1,0,6,Sunday,...,2015-11-01,27.48,83.34,14.03,0.72,0,0,0,NaN,0
1,2015-11-01 01:00:00,1,13,20151101011,2015,11,1,1,6,Sunday,...,2015-11-01,24.31,65.93,10.55,1.80,0,0,0,NaN,0
2,2015-11-01 02:00:00,1,10,20151101021,2015,11,1,2,6,Sunday,...,2015-11-01,28.24,36.81,24.00,0.97,0,0,0,NaN,0
3,2015-11-01 03:00:00,1,7,20151101031,2015,11,1,3,6,Sunday,...,2015-11-01,32.62,38.05,16.15,0.82,0,0,0,NaN,0
4,2015-11-01 04:00:00,1,9,20151101041,2015,11,1,4,6,Sunday,...,2015-11-01,23.83,67.43,9.73,1.67,0,0,0,NaN,0

#### Now the pipeline is:

#### Traffic Data
       ↓
#### Weather Data
       ↓
#### Event Data
       ↓
#### Unified Dataset

In [87]:
merged_df[
    [
        "DateTime",
        "Date",
        "Vehicles",
        "Temperature",
        "Precipitation",
        "HasEvent"
    ]
].head(10)

,DateTime,Date,Vehicles,Temperature,Precipitation,HasEvent
0,2015-11-01 00:00:00,2015-11-01,15,27.48,0.72,0
1,2015-11-01 01:00:00,2015-11-01,13,24.31,1.80,0
2,2015-11-01 02:00:00,2015-11-01,10,28.24,0.97,0
3,2015-11-01 03:00:00,2015-11-01,7,32.62,0.82,0
4,2015-11-01 04:00:00,2015-11-01,9,23.83,1.67,0
5,2015-11-01 05:00:00,2015-11-01,6,23.83,0.50,0
6,2015-11-01 06:00:00,2015-11-01,9,32.90,3.59,0
7,2015-11-01 07:00:00,2015-11-01,8,28.84,0.80,0
8,2015-11-01 08:00:00,2015-11-01,11,22.65,1.50,0
9,2015-11-01 09:00:00,2015-11-01,12,27.71,6.05,0

In [88]:
merged_df.isnull().sum()

DateTime                   0
Junction                   0
Vehicles                   0
ID                         0
Year                       0
Month                      0
Day                        0
Hour                       0
DayOfWeek                  0
DayName                    0
IsWeekend                  0
Date                       0
Temperature                0
Humidity                   0
WindSpeed                  0
Precipitation              0
SportsEvent                0
Concert                    0
PublicDemonstration        0
IsHoliday              48120
HasEvent                   0
dtype: int64

### IsHoliday That is intentional because the geographic location is unavailable

In [89]:
merged_df.duplicated().sum()

0

In [90]:
merged_df["ID"].duplicated().sum()

0

In [91]:
merged_df.shape

(48120, 21)

In [92]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DateTime             48120 non-null  datetime64[ns]
 1   Junction             48120 non-null  int64
 2   Vehicles             48120 non-null  int64
 3   ID                   48120 non-null  int64
 4   Year                 48120 non-null  int32
 5   Month                48120 non-null  int32
 6   Day                  48120 non-null  int32
 7   Hour                 48120 non-null  int32
 8   DayOfWeek            48120 non-null  int32
 9   DayName              48120 non-null  object
 10  IsWeekend            48120 non-null  int32
 11  Date                 48120 non-null  datetime64[ns]
 12  Temperature          48120 non-null  float64
 13  Humidity             48120 non-null  float64
 14  WindSpeed            48120 non-null  float64
 15  Precipitation        48120 non-null  float64
 16  SportsEvent          48120 non-null  int32
 17  Concert              48120 non-null  int32
 18  PublicDemonstration  48120 non-null  int32
 19  IsHoliday            0 non-null      float64
 20  HasEvent             48120 non-null  int32
dtypes: datetime64[ns](2), float64(5), int32(10), int64(3), object(1)
memory usage: 5.9+ MB

In [ ]:
# Because the country is unknown, I am going to  drop IsHoliday from model training

In [93]:
merged_df.drop(
    columns=["IsHoliday"],
    inplace=True
)

#### Standardize numerical features

In [95]:
from sklearn.preprocessing import StandardScaler

In [96]:
scale_columns = [
    "Temperature",
    "Humidity",
    "WindSpeed",
    "Precipitation"
]

In [97]:
scaler = StandardScaler()

In [98]:
merged_df[scale_columns] = scaler.fit_transform(
    merged_df[scale_columns]
)

In [99]:
merged_df[scale_columns].head()

   Temperature  Humidity  WindSpeed  Precipitation
0     0.497935  1.243730   0.401022      -0.524495
1    -0.139092  0.067627  -0.296367       0.205979
2     0.650660 -1.899525   2.399000      -0.355404
3     1.530843 -1.815759   0.825867      -0.456858
4    -0.235551  0.168957  -0.460694       0.118051

In [101]:
# EVERY THING SCALED TO 1

In [100]:
# merged_df.to_csv(
#     "final_unified_traffic_dataset.csv",
#     index=False
# )

In [102]:
merged_df.head()

,DateTime,Junction,Vehicles,ID,Year,Month,Day,Hour,DayOfWeek,DayName,IsWeekend,Date,Temperature,Humidity,WindSpeed,Precipitation,SportsEvent,Concert,PublicDemonstration,HasEvent
0,2015-11-01 00:00:00,1,15,20151101001,2015,11,1,0,6,Sunday,1,2015-11-01,0.497935,1.243730,0.401022,-0.524495,0,0,0,0
1,2015-11-01 01:00:00,1,13,20151101011,2015,11,1,1,6,Sunday,1,2015-11-01,-0.139092,0.067627,-0.296367,0.205979,0,0,0,0
2,2015-11-01 02:00:00,1,10,20151101021,2015,11,1,2,6,Sunday,1,2015-11-01,0.650660,-1.899525,2.399000,-0.355404,0,0,0,0
3,2015-11-01 03:00:00,1,7,20151101031,2015,11,1,3,6,Sunday,1,2015-11-01,1.530843,-1.815759,0.825867,-0.456858,0,0,0,0
4,2015-11-01 04:00:00,1,9,20151101041,2015,11,1,4,6,Sunday,1,2015-11-01,-0.235551,0.168957,-0.460694,0.118051,0,0,0,0

In [103]:
merged_df.shape

(48120, 20)